"""memrelay command-line interface (SPEC §7).

E0 wired the command surface and a working ``config`` command. This wave (E6/E7
walking skeleton) implements ``init``/``start``/``stop``/``status``/``mcp`` plus a
hidden ``_serve`` foreground runner; ``forget``/``seed`` remain stubs for later
epics. Daemon/MCP wiring is imported lazily inside each command so lightweight
commands (``config``, ``--help``) stay fast.
"""

from __future__ import annotations

import json
import os
from pathlib import Path

import click

from memrelay import __version__
from memrelay.config import Config, ensure_home, load_config
from memrelay.providers.copilot import CopilotProvider

_NOT_YET = "not implemented yet in this E0 foundations build"

#: Starter config written by ``init`` (mirrors the built-in defaults; SPEC §6).
DEFAULT_CONFIG_TOML = """\
# memrelay configuration (generated by `memrelay init`).
# Every value below is a built-in default; edit as needed. See SPEC §6.

[graph]
backend = "kuzu"
path = "~/.memrelay/graph.db"

[llm]
# borrow-host reuses the host agent's own model (no API keys). See SPEC §6.2.
strategy = "borrow-host"
host = "copilot"

[embeddings]
provider = "local"
model = "BAAI/bge-small-en-v1.5"

[ingest]
enable_phase = false
enable_boundary = false
"""


def _todo(command: str, epic: str) -> None:
    """Emit a uniform placeholder message for a not-yet-built subcommand."""
    click.echo(f"memrelay {command}: {_NOT_YET} (planned for {epic}).")


def _write_default_config(home) -> tuple[object, bool]:
    """Write the starter config into ``home`` if absent (idempotent).

    Returns ``(path, created)`` — ``created`` is False when a config already
    existed, so ``init`` never clobbers a user's edits.
    """
    path = home / "config.toml"
    if path.exists():
        return path, False
    path.write_text(DEFAULT_CONFIG_TOML, encoding="utf-8")
    return path, True


def _select_session(provider: CopilotProvider, session_id: str | None):
    """Pick the session to observe: ``session_id`` if given, else the most recent.

    Multi-session / continuous observation is the daemon epic (#8); here we observe a
    single discovered session, defaulting to the one whose trace was updated last.
    """
    refs = list(provider.discover_sessions())
    if session_id is not None:
        return next((ref for ref in refs if ref.session_id == session_id), None)
    if not refs:
        return None
    return max(refs, key=lambda ref: os.path.getmtime(ref.path) if ref.path else 0.0)


def _open_spool(db_path: Path):
    """Open session B's durable ``Spool`` at ``db_path`` (lazy import: B-owned)."""
    from memrelay.ingest.spool import Spool

    return Spool(str(db_path))


@click.group(context_settings={"help_option_names": ["-h", "--help"]})
@click.version_option(__version__, prog_name="memrelay")
def main() -> None:
    """Portable, graph-based persistent memory for AI coding agents."""


@main.command()
@click.option(
    "--copilot-home",
    "copilot_home",
    type=click.Path(file_okay=False),
    default=None,
    envvar="MEMRELAY_COPILOT_HOME",
    help="Copilot CLI home to register into (default ~/.copilot).",
)
def init(copilot_home: str | None) -> None:
    """First-time setup: create dirs, generate config, register MCP server."""
    cfg = load_config()
    home = ensure_home(cfg)
    config_file, created = _write_default_config(home)

    provider = CopilotProvider(copilot_home) if copilot_home else CopilotProvider()
    mcp_path = provider.register()

    click.echo(f"memrelay home:  {home}")
    click.echo(f"config:         {config_file}" + ("" if created else "  (kept existing)"))
    click.echo(f"registered MCP: {mcp_path}")
    click.echo("Run `memrelay start` to launch the observation daemon.")


@main.command()
def start() -> None:
    """Start the observation daemon (background process)."""
    from memrelay.daemon import lifecycle

    cfg = load_config()
    if lifecycle.is_running(cfg.home_path):
        pid = lifecycle.read_pid(cfg.home_path)
        suffix = f" (pid {pid})" if pid is not None else ""
        click.echo(f"memrelay daemon already running{suffix}.")
        return
    try:
        st = lifecycle.start_daemon(cfg)
    except lifecycle.DaemonStartError as exc:
        raise click.ClickException(str(exc)) from exc
    click.echo(f"memrelay daemon started (pid {st.pid}).")


@main.command()
def stop() -> None:
    """Stop the daemon gracefully."""
    from memrelay.daemon import lifecycle

    cfg = load_config()
    if lifecycle.stop_daemon(cfg):
        click.echo("memrelay daemon stopped.")
    else:
        click.echo("memrelay daemon is not running.")


@main.command()
def status() -> None:
    """Show daemon health: sessions observed, episodes ingested, spool depth."""
    from memrelay.daemon import lifecycle

    cfg = load_config()
    st = lifecycle.status(cfg)
    if not st.running:
        click.echo("memrelay daemon: not running")
        return
    health = st.health or {}
    click.echo("memrelay daemon: running")
    if st.pid is not None:
        click.echo(f"  pid:               {st.pid}")
    click.echo(f"  sessions_observed: {health.get('sessions_observed', 0)}")
    click.echo(f"  episodes_ingested: {health.get('episodes_ingested', 0)}")
    click.echo(f"  spool_pending:     {health.get('spool_pending', 0)}")


@main.command()
@click.option(
    "--session",
    "session_id",
    metavar="ID",
    default=None,
    help="Session to observe (default: the most recently updated one).",
)
@click.option(
    "--spool",
    "spool_path",
    type=click.Path(dir_okay=False),
    default=None,
    help="Spool database path (default: <home>/spool/spool.db).",
)
@click.option(
    "--copilot-home",
    "copilot_home",
    type=click.Path(file_okay=False),
    default=None,
    envvar="MEMRELAY_COPILOT_HOME",
    help="Copilot CLI home to observe (default ~/.copilot).",
)
def observe(session_id: str | None, spool_path: str | None, copilot_home: str | None) -> None:
    """Observe a Copilot session: map visible events to episodes in the spool.

    Replays one discovered session through the observation pipeline, writing an
    episode record for every visible, content-bearing message to the durable spool
    (idempotent — re-running never double-ingests). Continuous multi-session
    observation is the daemon epic; this is the one-shot capture.
    """
    import asyncio

    from memrelay.ingest.graphiti_sink import run_observe

    cfg = load_config()
    provider = CopilotProvider(copilot_home) if copilot_home else CopilotProvider()

    ref = _select_session(provider, session_id)
    if ref is None:
        raise click.ClickException(
            f"no Copilot session found with id {session_id!r}."
            if session_id
            else "no Copilot sessions found to observe."
        )

    home = ensure_home(cfg)
    # Frozen contract: the daemon ingester drains <home>/spool/spool.db (note the
    # "spool/" subdir). Observe MUST write the same file or ingest silently recalls
    # nothing. sqlite won't create the parent dir, so make it here.
    db_path = Path(spool_path) if spool_path else home / "spool" / "spool.db"
    db_path.parent.mkdir(parents=True, exist_ok=True)
    spool = _open_spool(db_path)

    result = asyncio.run(
        run_observe(ref.path, ref.session_id, spool=spool, provider=provider, config=cfg)
    )

    click.echo(f"observed session {result.session_id}")
    click.echo(f"  namespace: {result.namespace}")
    click.echo(f"  repo:      {result.repo}")
    click.echo(f"  parsed:    {result.parsed}")
    click.echo(f"  episodes:  {result.appended}")
    click.echo(f"  skipped:   {result.skipped}")
    click.echo(f"  spool:     {db_path}")


@main.command()
@click.option("--repo", metavar="OWNER/NAME", help="Delete all episodes from a specific repo.")
@click.option("--namespace", metavar="NAME", help="Delete an entire namespace graph.")
def forget(repo: str | None, namespace: str | None) -> None:
    """Delete memories for a repo or namespace."""
    if not repo and not namespace:
        raise click.UsageError("provide --repo OWNER/NAME or --namespace NAME")
    _todo("forget", "the retrieval/lifecycle epic")


@main.command()
def seed() -> None:
    """Ingest git history as episodes (bootstrap memory for existing repos)."""
    _todo("seed", "the retrieval epic")


@main.command(name="config")
@click.option(
    "--path",
    "config_path",
    type=click.Path(dir_okay=False),
    default=None,
    help="Load a specific config file instead of the default search path.",
)
def config_cmd(config_path: str | None) -> None:
    """Show the current (resolved) configuration as JSON."""
    cfg: Config = load_config(path=config_path)
    resolved = cfg.to_dict()
    # Surface fully-expanded paths alongside the raw template values.
    resolved["home_path"] = str(cfg.home_path)
    resolved["graph"]["resolved_path"] = str(cfg.graph_path)
    click.echo(json.dumps(resolved, indent=2))


@main.command()
def mcp() -> None:
    """Start the MCP stdio server (invoked by the agent, not by users)."""
    # stdout is the MCP transport here — must not print anything to it.
    from memrelay.mcp.server import run_stdio

    run_stdio()


@main.command(name="_serve", hidden=True)
def serve() -> None:
    """(internal) Run the daemon in the foreground; spawned by `memrelay start`."""
    from memrelay.daemon.lifecycle import run_foreground

    run_foreground(load_config())


if __name__ == "__main__":
    main()
