"""memrelay command-line interface (SPEC §7).

E0 wired the command surface and a working ``config`` command. This wave (E6/E7
walking skeleton) implements ``init``/``start``/``stop``/``status``/``mcp`` plus a
hidden ``_serve`` foreground runner; ``forget``/``seed`` remain stubs for later
epics. Daemon/MCP wiring is imported lazily inside each command so lightweight
commands (``config``, ``--help``) stay fast.
"""

from __future__ import annotations

import json
import os
from pathlib import Path

import click

from memrelay import __version__, guidance
from memrelay.config import Config, ensure_home, load_config
from memrelay.providers.base import AgentProvider, LLMStrategyHint
from memrelay.providers.registry import DEFAULT_PROVIDER_ID, get_registry

_NOT_YET = "not implemented yet in this E0 foundations build"

#: Starter config written by ``init`` (mirrors the built-in defaults; SPEC §6). The
#: ``[llm]`` block is rendered from the resolved provider's advertised default strategy
#: (SPEC §2.1 #2) via :func:`_render_config`, so a non-Copilot agent's ``init`` writes its
#: own host without a central edit.
_CONFIG_TEMPLATE = """\
# memrelay configuration (generated by `memrelay init`).
# Every value below is a built-in default; edit as needed. See SPEC §6.

[graph]
backend = "ladybug"
path = "~/.memrelay/graph.db"

[llm]
# borrow-host reuses the host agent's own model (no API keys). See SPEC §6.2.
strategy = "{strategy}"
{host_line}[embeddings]
provider = "local"
model = "BAAI/bge-small-en-v1.5"

[ingest]
enable_phase = false
enable_boundary = false
"""


def _render_config(hint: LLMStrategyHint) -> str:
    """Render the starter config, filling ``[llm]`` from the provider's strategy hint."""
    host_line = f'host = "{hint.host}"\n\n' if hint.host else "\n"
    return _CONFIG_TEMPLATE.format(strategy=hint.strategy, host_line=host_line)


def _resolve_provider(copilot_home: str | None) -> AgentProvider:
    """Resolve the agent provider through the registry (SPEC §2.1).

    An explicit ``--copilot-home`` targets the reference provider directly; otherwise the
    registry auto-detects the present agent, falling back to the default provider so
    behavior is unchanged on a machine where nothing is detected.
    """
    registry = get_registry()
    if copilot_home:
        return registry.create(DEFAULT_PROVIDER_ID, home=copilot_home)
    return registry.resolve()


def _todo(command: str, epic: str) -> None:
    """Emit a uniform placeholder message for a not-yet-built subcommand."""
    click.echo(f"memrelay {command}: {_NOT_YET} (planned for {epic}).")


def _model_cache_populated(cfg: Config) -> bool:
    """Best-effort: True if the embedding-model cache dir already holds files.

    Used only to keep an ``init`` re-run fast and to word the console message; the
    daemon's own embedder construction is the real guarantee the model is usable.
    """
    models_dir = cfg.home_path / "models"
    return models_dir.is_dir() and any(models_dir.iterdir())


def _embedding_model_size_hint(model_name: str) -> str:
    """Human-readable size suffix for the download message ('' when unknown).

    Reads fastembed's model registry (no download); any failure — including the
    lazy fastembed import itself — yields an empty hint, never an error.
    """
    try:
        from fastembed import TextEmbedding

        for entry in TextEmbedding.list_supported_models():
            model = entry.get("model") if isinstance(entry, dict) else getattr(entry, "model", None)
            if model != model_name:
                continue
            size = (
                entry.get("size_in_GB")
                if isinstance(entry, dict)
                else getattr(entry, "size_in_GB", None)
            )
            if size:
                return f", ~{round(float(size) * 1024)} MB"
    except Exception:  # noqa: BLE001 - the size hint is cosmetic; never fail init over it
        pass
    return ""


def _prefetch_embedding_model(cfg: Config) -> None:
    """Trigger the one-time embedding-model download so first run is self-contained (#13).

    Constructing the local embedder makes fastembed download the quantized ONNX model and
    cache it under ``<home>/models``; a re-run with the model already cached neither
    re-downloads nor reconstructs (kept fast). Only the key-less ``local`` provider has a
    model to fetch — byo-key providers resolve lazily and need no local download.

    Failure is non-fatal by contract: ``init`` has already created the home, written the
    config, and registered the MCP server, so a download problem (offline, a missing
    dependency, disk) only prints a warning and defers the fetch to first daemon use.
    """
    provider = (cfg.embeddings.provider or "local").lower()
    if provider != "local":
        click.echo(f"embedding model: none to prefetch (provider {provider!r}).")
        return
    if _model_cache_populated(cfg):
        click.echo("embedding model: already present (skipping download).")
        return

    model_name = cfg.embeddings.model
    size_hint = _embedding_model_size_hint(model_name)
    click.echo(f"embedding model: downloading {model_name} (one-time{size_hint})...")
    try:
        # Lazy import: keeps `--help`/`config` fast and confines the fastembed/onnxruntime
        # dependency to the one command that needs it.
        from memrelay.engine.graphiti import build_embedder

        build_embedder(cfg)  # constructing the embedder is the download trigger
    except Exception as exc:  # noqa: BLE001 - any failure must not abort init
        click.echo(
            f"embedding model: could not download now ({exc}); memrelay will fetch it "
            "automatically on first use (needs network).",
            err=True,
        )
        return
    click.echo("embedding model: done.")


def _prefetch_fts_extension(cfg: Config) -> None:
    """Warm Ladybug's FTS-extension cache so the first ``start`` does not race the network (#93).

    On a cold first run the daemon builds the full engine — including a first-time network
    fetch of Ladybug's FTS extension (the #76 TLS-workaround path) — before it serves health,
    so ``start``'s fixed readiness window can elapse mid-download and report a spurious
    failure. Warming the per-user cache here (mirroring the embedding-model prefetch, #13)
    makes the first ``start`` fully offline for FTS.

    Only the embedded ``ladybug`` backend loads this extension; the cloud opt-in backends have
    nothing to prefetch. Non-fatal by contract: the runtime loader keeps its native
    ``INSTALL FTS`` fallback, so a prefetch problem (offline, missing build) only prints a
    warning and defers the fetch to first daemon use.
    """
    backend = (cfg.graph.backend or "ladybug").lower()
    if backend != "ladybug":
        click.echo(f"FTS extension: none to prefetch (graph backend {backend!r}).")
        return

    click.echo("FTS extension: prefetching Ladybug full-text search (one-time)...")
    try:
        # Lazy import: keeps `--help`/`config` fast and confines the ladybug/network path to
        # the one command that needs it.
        from memrelay.engine.backends._fts_extension import prefetch_fts_extension

        prefetch_fts_extension()
    except Exception as exc:  # noqa: BLE001 - any failure must not abort init
        click.echo(
            f"FTS extension: could not prefetch now ({exc}); memrelay will fetch it "
            "automatically on first daemon start (needs network).",
            err=True,
        )
        return
    click.echo("FTS extension: ready.")


def _check_phase_bundle(cfg: Config) -> None:
    """Report phase-enrichment readiness during ``init`` (opt-in #98, mirrors #13/#93).

    Phase is off by default, so the common path just notes it is disabled. When an
    operator has set ``enable_phase = true`` this runs the same preflight the observe
    path uses (:func:`memrelay.ingest.phase_guard.resolve_phase` — load the traceforge
    phase bundle + one trial embed) and echoes whether it is ready. No download: the
    phase model and embedder ship inside traceforge. Non-fatal by contract — a not-ready
    result only warns; the daemon will still run (degrading that observe pass to
    phase-off) rather than crash.
    """
    if not cfg.ingest.enable_phase:
        click.echo("phase enrichment: disabled (enable_phase = false; opt-in).")
        return

    click.echo("phase enrichment: verifying traceforge phase model...")
    try:
        # Lazy import: confines the traceforge ML path to the one command that needs it.
        from memrelay.ingest.phase_guard import resolve_phase

        ready, _ = resolve_phase(cfg)
    except Exception as exc:  # noqa: BLE001 - readiness check must never abort init
        ready = False
        click.echo(f"phase enrichment: readiness check failed ({exc}).", err=True)
    if ready:
        click.echo("phase enrichment: ready (phase model + embedder loaded).")
    else:
        click.echo(
            "phase enrichment: enabled but not ready — episodes will store WITHOUT a "
            "phase. Install the optional stack (`pip install memrelay[phase]`) and ensure "
            "the traceforge phase bundle is present (or set $TRACEFORGE_PHASE_MODEL).",
            err=True,
        )


def _write_default_config(home, config_text: str) -> tuple[object, bool]:
    """Write the starter config into ``home`` if absent (idempotent).

    Returns ``(path, created)`` — ``created`` is False when a config already
    existed, so ``init`` never clobbers a user's edits.
    """
    path = home / "config.toml"
    if path.exists():
        return path, False
    path.write_text(config_text, encoding="utf-8")
    return path, True


def _select_session(provider: AgentProvider, session_id: str | None):
    """Pick the session to observe: ``session_id`` if given, else the most recent.

    Multi-session / continuous observation is the daemon epic (#8); here we observe a
    single discovered session, defaulting to the one whose trace was updated last.
    """
    refs = list(provider.discover_sessions())
    if session_id is not None:
        return next((ref for ref in refs if ref.session_id == session_id), None)
    if not refs:
        return None
    return max(refs, key=lambda ref: os.path.getmtime(ref.path) if ref.path else 0.0)


def _open_spool(db_path: Path):
    """Open session B's durable ``Spool`` at ``db_path`` (lazy import: B-owned)."""
    from memrelay.ingest.spool import Spool

    return Spool(str(db_path))


@click.group(context_settings={"help_option_names": ["-h", "--help"]})
@click.version_option(__version__, prog_name="memrelay")
def main() -> None:
    """Portable, graph-based persistent memory for AI coding agents."""


@main.command()
@click.option(
    "--copilot-home",
    "copilot_home",
    type=click.Path(file_okay=False),
    default=None,
    envvar="MEMRELAY_COPILOT_HOME",
    help="Copilot CLI home to register into (default ~/.copilot).",
)
def init(copilot_home: str | None) -> None:
    """First-time setup: create dirs, generate config, register MCP server."""
    cfg = load_config()
    home = ensure_home(cfg)

    provider = _resolve_provider(copilot_home)
    config_file, created = _write_default_config(home, _render_config(provider.llm_strategy()))
    mcp_path = provider.register()

    click.echo(f"memrelay home:  {home}")
    click.echo(f"config:         {config_file}" + ("" if created else "  (kept existing)"))
    click.echo(f"registered MCP: {mcp_path}")
    _prefetch_embedding_model(cfg)
    _prefetch_fts_extension(cfg)
    _check_phase_bundle(cfg)
    click.echo("Run `memrelay start` to launch the observation daemon.")


@main.command()
def start() -> None:
    """Start the observation daemon (background process)."""
    from memrelay.daemon import lifecycle

    cfg = load_config()
    if lifecycle.is_running(cfg.home_path):
        pid = lifecycle.read_pid(cfg.home_path)
        suffix = f" (pid {pid})" if pid is not None else ""
        click.echo(f"memrelay daemon already running{suffix}.")
        return
    try:
        st = lifecycle.start_daemon(cfg)
    except lifecycle.DaemonStartError as exc:
        raise click.ClickException(str(exc)) from exc
    click.echo(f"memrelay daemon started (pid {st.pid}).")


@main.command()
def stop() -> None:
    """Stop the daemon gracefully."""
    from memrelay.daemon import lifecycle

    cfg = load_config()
    if lifecycle.stop_daemon(cfg):
        click.echo("memrelay daemon stopped.")
    else:
        click.echo("memrelay daemon is not running.")


@main.command()
def status() -> None:
    """Show daemon health: sessions observed, episodes ingested, spool depth."""
    from memrelay.daemon import lifecycle

    cfg = load_config()
    st = lifecycle.status(cfg)
    if not st.running:
        click.echo("memrelay daemon: not running")
        return
    health = st.health or {}
    click.echo("memrelay daemon: running")
    if st.pid is not None:
        click.echo(f"  pid:               {st.pid}")
    click.echo(f"  sessions_observed: {health.get('sessions_observed', 0)}")
    click.echo(f"  episodes_ingested: {health.get('episodes_ingested', 0)}")
    click.echo(f"  spool_pending:     {health.get('spool_pending', 0)}")


@main.command()
@click.option(
    "--session",
    "session_id",
    metavar="ID",
    default=None,
    help="Session to observe (default: the most recently updated one).",
)
@click.option(
    "--spool",
    "spool_path",
    type=click.Path(dir_okay=False),
    default=None,
    help="Spool database path (default: <home>/spool/spool.db).",
)
@click.option(
    "--copilot-home",
    "copilot_home",
    type=click.Path(file_okay=False),
    default=None,
    envvar="MEMRELAY_COPILOT_HOME",
    help="Copilot CLI home to observe (default ~/.copilot).",
)
def observe(session_id: str | None, spool_path: str | None, copilot_home: str | None) -> None:
    """Observe a Copilot session: map visible events to episodes in the spool.

    Replays one discovered session through the observation pipeline, writing an
    episode record for every visible, content-bearing message to the durable spool
    (idempotent — re-running never double-ingests). Continuous multi-session
    observation is the daemon epic; this is the one-shot capture.
    """
    import asyncio

    from memrelay.ingest.graphiti_sink import run_observe

    cfg = load_config()
    provider = _resolve_provider(copilot_home)

    ref = _select_session(provider, session_id)
    if ref is None:
        raise click.ClickException(
            f"no Copilot session found with id {session_id!r}."
            if session_id
            else "no Copilot sessions found to observe."
        )

    home = ensure_home(cfg)
    # Frozen contract: the daemon ingester drains <home>/spool/spool.db (note the
    # "spool/" subdir). Observe MUST write the same file or ingest silently recalls
    # nothing. sqlite won't create the parent dir, so make it here.
    db_path = Path(spool_path) if spool_path else home / "spool" / "spool.db"
    db_path.parent.mkdir(parents=True, exist_ok=True)
    spool = _open_spool(db_path)

    # Observe consumes the [namespaces.*] map here; the MCP recall path
    # (build_mcp_server/run_stdio) does not thread it yet — tracked in #106.
    result = asyncio.run(
        run_observe(
            ref.path,
            ref.session_id,
            spool=spool,
            provider=provider,
            config=cfg,
            namespace_map=cfg.namespaces.repo_map,
        )
    )

    click.echo(f"observed session {result.session_id}")
    click.echo(f"  namespace: {result.namespace}")
    click.echo(f"  repo:      {result.repo}")
    click.echo(f"  parsed:    {result.parsed}")
    click.echo(f"  episodes:  {result.appended}")
    click.echo(f"  skipped:   {result.skipped}")
    click.echo(f"  spool:     {db_path}")


@main.command(name="guidance")
@click.option(
    "--target",
    type=click.Choice(sorted(guidance.TARGETS)),
    default=guidance.DEFAULT_TARGET,
    show_default=True,
    help="Which repo-local agent instruction file to update.",
)
@click.option(
    "--path",
    "explicit_path",
    type=click.Path(dir_okay=False),
    default=None,
    help="Write to this exact instruction file instead of the --target default.",
)
@click.option("--dry-run", is_flag=True, help="Preview the change and exit; write nothing.")
@click.option("--yes", "-y", is_flag=True, help="Skip the confirmation prompt (non-interactive).")
def guidance_cmd(target: str, explicit_path: str | None, dry_run: bool, yes: bool) -> None:
    """Append opt-in memrelay recall guidance to an agent's instructions file.

    Writes a short, marked block telling the agent when and how to use memrelay's
    ``memory_recall`` / ``memory_detail`` / ``memory_note`` tools, so it actually recalls
    prior context at the right moments. Opt-in and non-destructive: nothing is written
    without your explicit confirmation (or ``--yes``), the block is fenced so a re-run
    updates it in place instead of duplicating, and content outside the block is never
    touched. Use ``--dry-run`` to preview the exact block and target without writing.

    The default target is a repo-local ``AGENTS.md`` in the current directory (run from
    your repo root); ``--target`` selects another supported agent's file and ``--path``
    points at any explicit instruction file.
    """
    path = (
        Path(explicit_path) if explicit_path else guidance.resolve_target_path(target, Path.cwd())
    )

    try:
        preview = guidance.apply_guidance(path, write=False)
    except guidance.MalformedMarkersError as exc:
        raise click.ClickException(str(exc)) from exc

    click.echo(f"target: {path}")
    click.echo(f"action: {preview.action.value}")
    click.echo("")
    click.echo(guidance.render_block())
    click.echo("")

    if dry_run:
        click.echo("dry run: nothing written.")
        return
    if preview.action is guidance.Action.UNCHANGED:
        click.echo(f"{path}: already up to date.")
        return
    if not yes and not click.confirm(f"Write memrelay guidance to {path}?"):
        click.echo("aborted: nothing written.")
        return

    result = guidance.apply_guidance(path, write=True)
    click.echo(f"{result.action.value}: {path}")


@main.command()
@click.option("--repo", metavar="OWNER/NAME", help="Delete all episodes from a specific repo.")
@click.option("--namespace", metavar="NAME", help="Delete an entire namespace graph.")
def forget(repo: str | None, namespace: str | None) -> None:
    """Delete memories for a repo or namespace."""
    if not repo and not namespace:
        raise click.UsageError("provide --repo OWNER/NAME or --namespace NAME")
    _todo("forget", "the retrieval/lifecycle epic")


@main.command()
def seed() -> None:
    """Ingest git history as episodes (bootstrap memory for existing repos)."""
    _todo("seed", "the retrieval epic")


@main.command(name="config")
@click.option(
    "--path",
    "config_path",
    type=click.Path(dir_okay=False),
    default=None,
    help="Load a specific config file instead of the default search path.",
)
def config_cmd(config_path: str | None) -> None:
    """Show the current (resolved) configuration as JSON."""
    cfg: Config = load_config(path=config_path)
    resolved = cfg.to_dict()
    # Surface fully-expanded paths alongside the raw template values.
    resolved["home_path"] = str(cfg.home_path)
    resolved["graph"]["resolved_path"] = str(cfg.graph_path)
    click.echo(json.dumps(resolved, indent=2))


@main.command()
def mcp() -> None:
    """Start the MCP stdio server (invoked by the agent, not by users)."""
    # stdout is the MCP transport here — must not print anything to it.
    from memrelay.mcp.server import run_stdio

    run_stdio()


@main.command(name="_serve", hidden=True)
def serve() -> None:
    """(internal) Run the daemon in the foreground; spawned by `memrelay start`."""
    from memrelay.daemon.lifecycle import run_foreground

    run_foreground(load_config())


if __name__ == "__main__":
    main()
